config/routes.rb
Rails.application.routes.draw do

  get 'help/index'

  namespace :administrator do
  get 'sections/_section'
  end

  namespace :administrator do
  get 'sections/index'
  end

  namespace :administrator do
  get 'sections/show'
  end

  namespace :administrator do
  get 'students/index'
  end

  namespace :administrator do
  get 'students/_student'
  end

  namespace :administrator do
  get 'students/show'
  end

  namespace :administrator do
  get 'students/edit'
  end
  
  namespace :administrator do
  get 'admin_section_preferences/_admin_section_preferences'
  end

  namespace :administrator do
  get 'admin_section_preferences/index'
  end

  namespace :administrator do
  get 'admin_section_preferences/show'
  end

  get 'white_courses/index'

  get 'courses/Sync'

  get 'courses/index'

  root 'pages#index'

  devise_for :users, :controllers => {
    :omniauth_callbacks => "users/omniauth_callbacks"
  }

  resources :skills
  
  resources :student do 
  	
  	  # Students
  	resources :section_preferences do 
    	collection do
    		post :collect_pref
    		
    	end
    end
  resources :experiences do
    	collection do
    		post :collect_experiences
    	end
    end
  	
  	
  end



  # Instructors
  resources :sections do
  	post :comment
    resources :student_preferences do 
    	collection do
    		
    		post :collect_pref
    		
    	end
    end
    
    resources :requirements do
    	collection do
    		post :collect_requirements
    	end
    end
  end

  namespace :administrator do

    resources :departments
    resources :section_imports
    resources :white_courses do 
    	collection do
	    	post :update_term
	    	put :ignoreSelectedCourses
	    	put :backSelectedCourses
	        post :cross
	        post :config_constants
	        get :cross_listed
    	end
    
    delete :deleteCross
    	
   end
    
    resources :courses do
    	collection do
    		delete :deleteAllSections
	    	get :editAll
	    	get :deleteSections
	    	post :create
	    	delete :deleteSelectedSections
	    	get :adjustSections
	    	put :adjustSelectedSections 
	    	post :updateSectionsInfo
	    	post :do_update_Sections
    	end
    end
    resources :sections
    resources :email do
      collection do
        post  :sendmail
        end
      end
    resources :keep_users do 
    	collection do
   			 post :addUsers
  		end
    end
    resources :users do
    	collection do
    		delete :destroyAll
    		put :reset
  		end
  	
  	
  		put :wait_list
  		put :off_wait_list
  		put :un_consider

     end
    
    resources :assignments do
    	get :no_stat_edit

      #collection do
        get :send_assignments_CS
        get :send_assignments_non_CS
      #end
    end

    resources :user_imports
    
    get 'settings' => 'settings#index'
    post 'settings/current_term' => 'settings#set_current_term'
    post 'settings/synchronizeGTA' => 'settings#synchronizeGTA'
   	post 'settings/synchronizeIns' => 'settings#synchronizeIns'
    post 'settings/synchronize' => 'settings#synchronize'
    get 'settings/section_preferences_cs' => 'settings#section_preferences_cs'
    get 'settings/section_preferences_ece' => 'settings#section_preferences_ece'
    get 'settings/student_preferences' => 'settings#student_preferences'
    get 'settings/sections' => 'settings#sections'
    get 'settings/gta_template' => 'user_imports#gta_template'
    get 'settings/instructor_template' => 'user_imports#instructor_template'
    get 'settings/sections_template' => 'courses#sections_template'


  end
 
   match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]
end

app/controllers/administrator/assignments_controller.rb
require 'integer_linear_program'
require 'solve_problem_job'

SolveProblemJob

module Administrator
  class AssignmentsController < BaseController
    before_action :set_students, only: [:new, :create, :update, :show,:no_stat_edit]
    before_action :set_sections, only: [:new, :create, :update, :show,:no_stat_edit,:send_assignments_CS,:send_assignments_non_CS]
    before_action :set_cut_off, only: [ :edit, :update, :show,:no_stat_edit]
    before_action :set_student_per_ta
    
    before_action :set_cs_students, only: [ :edit,:no_stat_edit,:send_assignments_CS,:send_assignments_non_CS]
    before_action :set_ece_students, only: [:edit,:no_stat_edit,:send_assignments_CS,:send_assignments_non_CS]
    before_action :set_cs_sections, only: [ :edit,:no_stat_edit]
    before_action :set_ece_sections, only: [ :edit,:no_stat_edit]

    def index
      @assignments = Assignment.order(created_at: :desc)
      @assignment = Assignment.new
      @assignments_fte = {}
      @assignments_is_fixed = {}

    end
   
   
   def destroy
   		Assignment.find(params[:id]).destroy
   		redirect_to administrator_assignments_path
   	end

    def new
      @assignment = Assignment.new
      @assignments_fte = {}
      @assignments_is_fixed = {}
     
      @doubles = []
      @ftes = []
   	@students.each do |student|
    		
    		if student.is_wait_list 
    			
    			@ftes.push(0)
          		@doubles.push("wait_list")
    		else
    			@doubles.push("")
    			@ftes.push("")
    		end
    	end
      	
    end

    def edit
      @assignment = Assignment.find(params[:id])
      @assignments_fte = @assignment.assignments_fte
      @assignments_is_fixed = @assignment.assignments_is_fixed
            
      set_doubles

    end
   
   def no_stat_edit
   	
   	 @assignment = Assignment.find(params[:assignment_id])
      @assignments_fte = @assignment.assignments_fte
      @assignments_is_fixed = @assignment.assignments_is_fixed

   	
   	end

    def create
    	
    redirect_to administrator_assignments_path

      @assignments_fte = params[:assignments_fte] || {}
      @assignments_is_fixed = params[:assignments_is_fixed] || {}
      @missing_fte = params[:missing_fte].to_f || 0.0


      if params[:commit] == "Run solver"
      	
      	#SolveProblemJob.perform_later(@students.to_json,@sections.to_json, @assignments_fte.to_json, @assignments_is_fixed.to_json )
        begin
          problem = ::IntegerLinearProgram.new(@students.gtas_approved, @sections, @assignments_fte, @assignments_is_fixed, {}, false)
          problem.solve
          @assignments_fte = problem.results
          #problem.print_results

        rescue RuntimeError
          flash[:alert] = "Infeasible solution"
        end
      end

     @assignment = Assignment.create( assignments_fte: @assignments_fte, assignments_is_fixed: @assignments_is_fixed)
#      redirect_to administrator_assignment_path(@assignment)
    end

    def update
    	   	  
   	  previous_assignments = Assignment.find(params[:id]).assignments_fte || {}
      @assignments_fte = params[:assignments_fte] || {}
      @assignments_is_fixed = params[:assignments_is_fixed] || {}
      @allow_double_ass = params[:assignment]["allow_double_ass"]
      
      submitted_assignments = submit_assignments( @assignments_fte, previous_assignments, @assignments_is_fixed )
      
    #  redirect_to administrator_assignments_path

      if params[:commit] == "Run solver"      	
        begin
        	
          problem = ::IntegerLinearProgram.new(@students.gtas_approved, @sections, submitted_assignments, @assignments_is_fixed ,  @allow_double_ass)
          problem.solve
          submitted_assignments = problem.results

        rescue RuntimeError
          flash[:alert] = "Infeasible solution"
        end
      end

      @assignment = Assignment.create(
        assignments_fte: submitted_assignments, assignments_is_fixed: @assignments_is_fixed, allow_double_ass: @allow_double_ass)
      redirect_to edit_administrator_assignment_path(@assignment)
      
    end

    def show
   		
      @assignment = Assignment.find(params[:id])
      @assignments_fte = @assignment.assignments_fte
      @assignments_is_fixed = @assignment.assignments_is_fixed

     # set_doubles

      respond_to do |format|
        format.html
        format.txt  { render 'show.txt.erb' }
        format.xlsx { render xlsx: 'show.xlsx.axlsx' }
      end
    end

    def send_assignments_CS
          subject = "Your GTA Assignment"
            
          @assignment = Assignment.find(params[:assignment_id])
          @assignments_fte = @assignment.assignments_fte

          has_assignment = false
          @cs_students.each do |student|
              has_assignment = false
              message = "Hello " + student.full_name + ",\n\n" 
            @sections.each do |section|
              if @assignments_fte["#{student.id}_#{section.id}"] && @assignments_fte["#{student.id}_#{section.id}"] > 0 and student.major == "CS" then
                assigned_course =  "#{section.merge_label} - #{section.section_name}"
                message += "For " + section.term + " term you are assigned:\n" + @assignments_fte["#{student.id}_#{section.id}"].to_s + " FTE to: " +
                            assigned_course + " (CRN: " + (section.crn).to_s + ")\n" 
                has_assignment = true
              end
            end
            if(has_assignment) then
              message += "\nIf you have any questions, please contact Dr. Tadepalli at Tadepall@oregonstate.edu.\n\n Thank you"
              #For Testing
              #recipients = "burnettn@oregonstate.edu"
              #To actually send TA Emails
              recipients = student.email #"ghadeeralkubaish@gmail.com" 
              Email.welcome_email(recipients, subject , message).deliver
            end
          end
   		 redirect_to administrator_assignments_path

    end

    def send_assignments_non_CS
          subject = "Your GTA Assignment"
            
          @assignment = Assignment.find(params[:assignment_id])
          @assignments_fte = @assignment.assignments_fte

          has_assignment = false
          @ece_students.each do |student|
              has_assignment = false
              message = "Hello " + student.full_name + ",\n\n" 
            @sections.each do |section|
              if @assignments_fte["#{student.id}_#{section.id}"] && @assignments_fte["#{student.id}_#{section.id}"] > 0 and student.major != "CS" then
                assigned_course =  "#{section.merge_label} - #{section.section_name}"
                message += "For " + section.term + " term you are assigned:\n" + @assignments_fte["#{student.id}_#{section.id}"].to_s + " FTE to: " +
                            assigned_course + " (CRN: " + (section.crn).to_s + ")\n" 
                has_assignment = true
              end
            end
            if(has_assignment) then
              message += "\nIf you have any questions, please contact Dr. Tadepalli at Tadepall@oregonstate.edu.\n\n Thank you"
              #For Testing
              #recipients = "burnettn@oregonstate.edu"
              #To actually send TA Emails
              recipients = student.email #"ghadeeralkubaish@gmail.com" 
              Email.welcome_email(recipients, subject , message).deliver
            end
          end
    	redirect_to administrator_assignments_path

    end  

    private
    
    
    def submit_assignments(assignments_fte, previous_assignments, assignments_is_fixed )
   	
   	   	fix_assignments = previous_assignments
 
	   	assignments_is_fixed.each do |key, value|
	      student_id, section_id = key.split("_")
	      
	      if ! assignments_fte["#{student_id}_#{section_id}"] 
	      	     fix_assignments[:"#{student_id}_#{section_id}"] = previous_assignments["#{student_id}_#{section_id}"]
		  else
		  		  fix_assignments[:"#{student_id}_#{section_id}"] = assignments_fte[:"#{student_id}_#{section_id}"]

	      end
	     
		end
	
   		return fix_assignments
   	end
   
    def set_cut_off
    	cut_off = Setting.where(var: "round_cut_off" ).take 
	 	@round_cut_off = cut_off  == nil ? 15.0 : cut_off.value.to_f
	 	@round = @round_cut_off / 100.0
    end
    def set_student_per_ta
    	 st_ta = Setting.where(var: "students_per_ta" ).take
		 @students_per_ta = Setting.where(var: "students_per_ta" ).take == nil ? 30.0 : st_ta.value.to_f
    end
   
   
   def set_cs_students
   	 @cs_students = User.includes([{section_preferences: :section}, :experiences]).cs_students
   	end


	def set_ece_students
	  @ece_students = User.includes([{section_preferences: :section}, :experiences]).ece_students
	end


	def set_cs_sections
	   	 @cs_sections = Section.includes(
		        {course: [:department]},
		        {instructor: :student_preferences}, :section_preferences)
		        .with_current_term
		        .order("departments.subject_code ASC,courses.course_number ASC")
		       	.where('courses.ignored = ?', false)
		       	.where(show: true).where("departments.subject_code =?", "CS")

	end

	def set_ece_sections
	   	 @ece_sections = Section.includes(
		        {course: [:department]},
		        {instructor: :student_preferences}, :section_preferences)
		        .with_current_term
		        .order("departments.subject_code ASC,courses.course_number ASC")
		       	.where('courses.ignored = ?', false)
		       	.where(show: true).where.not("departments.subject_code =?", "CS")

	end



    def set_sections
    	
    	@sections = Section.includes(
		        {course: [:department]},
		        {instructor: :student_preferences}, :section_preferences)
		        .with_current_term
		        .order("departments.subject_code ASC,courses.course_number ASC")
		       	.where('courses.ignored = ?', false)
		       	.where(show: true)
		      
    end
   
   def set_students
   	  @students = User.includes([{section_preferences: :section}, :experiences]).where(role: "Student", consider: true)
   	
   	end
    	
=begin    	
    	

app/controllers/administrator/base_controller.rb
module Administrator
  class BaseController < ::ApplicationController
    before_filter :authenticate
    before_filter :authorize

    def authenticate
      unless signed_in?
        return redirect_to root_path, alert: "Must be logged in."
      end
    end

    def authorize
      unless current_user.is_administrator
        return redirect_to root_path, alert: "Must be an administrator."
      end
    end
  end
end

app/controllers/administrator/email_controller.rb
module Administrator
	class EmailController < ApplicationController

	 # GET /admin/users/status
	    def index
	            if params[:status] == "all"
	              @users = User.all
	            elsif  params[:status] == "CS_Student"
	              @gta_users = User.where({role: "Student"})
	              		 @users = []
	              		 @gta_users.each do |usr|
	              		 	if usr.major == "CS"
	              		 		 @users.push(usr)
	              		 	end
	              		 end
	            elsif  params[:status] == "ECE_Student"
	              @gta_users = User.where({role: "Student"})
	              		 @users = []
	              		 @gta_users.each do |usr|
	              		 	if usr.major != "CS"
	              		 		 @users.push(usr)
	              		 	end
	              		 end
	            elsif  params[:status] == "Instructor" 
	              @users = User.where({role: "Instructor", consider: true})
	            elsif params[:status] == "sendToMissing" 
	              		@gta_users = User.where({role: "Student"})
	              		 @users = []
	              		 @gta_users.each do |usr|
	              		 	if usr.section_preferences == []
	              		 		 @users.push(usr)
	              		 	end
	              		 end
	            else
	              @users = User.where :role => "Administrator"
	            end  

	            #render :file => 'app\views\administrator\email\index.html.erb'  
   		end

    	def sendmail
		      object = params[:email]
		      recipients = object[:recipient]
		      subject = object[:subject]
		      message = object[:message]
		      #Email.contact(recipient, subject, message).deliver
		      #return if request.xhr?

		      render :text => "Message Sent"
		      Email.welcome_email(recipients, subject , message).deliver
   		end

   	#	def send_assignments
	#	      object = params[:email]
	#	      recipients = object[:recipient]
	#	      subject = object[:subject]
	#	      message = object[:message]
	#	      #Email.contact(recipient, subject, message).deliver
	#	      #return if request.xhr?
#
	#	      render :text => "Message Sent"
	#	      Email.welcome_email(recipients, subject , message).deliver
   	#	end
	end
end

app/controllers/administrator/section_imports_controller.rb
module Administrator
	class SectionImportsController < BaseController
  	
 	 def index   		
   	@section_import = SectionImport.new
  end
 
  def new   		
   	@section_import = SectionImport.new
  end
 
 def create
    @section_import = SectionImport.new(params[:section_import])
    
    if @section_import.save
    	update_Sections
      redirect_to editAll_administrator_courses_path, notice: "Imported sections successfully."
    else    	
    	 redirect_to editAll_administrator_courses_path, alert: "Error: " + @section_import.errors.full_messages.join(', ').html_safe 
    end
   
  end
 
  def update_Sections
  		@sections = Section.all
		@sections.each do |s|
			s.update_sections
		end
  end
 
 	 def user_params
        params[:section_import].permit(:file)
      end
     
     end
 end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/administrator/admin_section_preferences_helper.rb
module Administrator::AdminSectionPreferencesHelper
end

app/helpers/administrator/sections_helper.rb
module Administrator::SectionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/administrator/users/_form.html.erb
<%= form_for [:administrator, @user] do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@user.errors.count, "error") %>
        prohibited this user from being saved:
      </h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="form-group">
    <label>OSU ID</label>
    <%= f.number_field :osu_id, class: "form-control" %>
  </div>

  <div class="form-group">
    <label>First Name</label>
    <%= f.text_field :first_name, class: "form-control" %>
  </div>

  <div class="form-group">
    <label>Last Name</label>
    <%= f.text_field :last_name, class: "form-control" %>
  </div>

  <div class="form-group">
 
     <label>Emails</label>
         <span class="help-block">Email <strong>must</strong> be of the form <code>@oregonstate.edu</code> and match this user's ONID username. Failure to follow this convention will result in data synchronization errors.</span>

     
     <div>
    <%= f.fields_for :gemails do |email_f| %>
      <%= render 'gemail_fields', f: email_f %>
    <% end %>

   <div class="links">
      <%= link_to_add_association 'Add Additional Email', f, :gemails %>
    </div>
    
  </div>

 
  </div>
  
  

    <% if (params[:status] == "Student") || (@user.notRegistred && ! @user.new_record?) %>
    <div class="form-group">
       <%= f.label :fte %>
     <%= f.number_field :fte, step: 0.25, min: 0.25, max: 0.5, :value => 0.25 %>
    <br><br><label>Is student in wait-list </label>
     <%= f.check_box :is_wait_list %> 
  <br><br><label>Major </label>
     <%= f.select :major , ["CS","ECE"], :selected => @user.major %> 

  </div>
   <% end %>
   
     <label>Role </label>
     <%= f.select :role , ["Student","Instructor","Administrator"],  :selected =>  @user.role %> 
      <br><br>
      
       <label>Consider </label>
          <%= f.check_box :consider, :value => true %> 
      <br><br>
      
       <label>Is Admin </label>
          <%= f.check_box :is_administrator, :value => true %> 
      <br><br>

  <div class="actions">
    <%= f.submit nil, class: "btn btn-default" %>

    <% unless @user.new_record? %>
    
	<div class = "pull-right">
	       <%= link_to "Delete", administrator_user_path(@user, :status => params[:status]), method: :delete,
	        data: {confirm: "Are you sure?"}, class: "btn btn-danger " %>
	 
	     <%= link_to "Ignore", administrator_user_un_consider_path(@user, :status => params[:status]), method: :put,
	        data: {confirm: "Are you sure?"}, class: "btn btn-warning" %>
	</div>

    <% end %>
    
    
  </div>
<% end %>

app/views/administrator/users/_gemail_fields.html.erb
<div class="nested-fields">
  <div>
      <%= f.label :email %>
      <%= f.email_field :email %>
  
      <%= link_to_remove_association "remove email", f %>
  </div>
</div>

app/views/administrator/users/_user.html.erb
<tr class= <%= user.is_wait_list ? "warning" :"" %> <%= user.notRegistred ? "danger" :"" %> >
  <td><%= @i %></td>
  <td><%= user.osu_id %></td>
  <td><%= link_to user.first_name, edit_administrator_user_path(user, :status => params[:status]) %></td>
  <td><%= link_to user.last_name, edit_administrator_user_path(user, :status => params[:status]) %></td>
  <td><%= user.emails.to_sentence(two_words_connector: ' , ')%></td>
  <td><%= user.role %></td>
  <% if params[:status] == "Student" %>
  <td><%= user.fte %></td>
  <td><%= user.major %></td>
  <td><%= user.is_wait_list %></td>
  <td><%= user.is_administrator %></td>

    <td>
   	
   	<% if user.is_wait_list %>
   	
   	 <%= link_to "out wait-list", administrator_user_off_wait_list_path(user, :status => params[:status]), method: :put,
        data: {confirm: "Are you sure?"}, class: "btn btn-success pull-right" %>
        
  
        <%else%>	
        
         <%= link_to "in wait-list", administrator_user_wait_list_path(user, :status => params[:status]), method: :put,
        data: {confirm: "Are you sure?"}, class: "btn btn-warning pull-right" %>
        
        <%end%>
       	
        </td>
   <%end%>
   
     <% if params[:status] == "all" %>
  <td><%= user.is_administrator %></td>
  <td><%= user.consider %></td>
<%end%> 

</tr>
<% @i +=1 %>

app/views/administrator/users/edit.html.erb
<%= link_to "&larr; Back to Users".html_safe, administrator_users_path(:status => params[:status] ) %>

<h1>Editing User</h1>

<%= render 'form' %>


 <div>

<hr class="divider">
<% if @user.is_student %>
 
 <br>
<label class="control-label-static">Experience</label>
  <ul class="list-group">
    <% @user.experiences.each do |experience| %>
      <li class="list-group-item">
        <span class="label label-primary"><%= experience.value %></span>
        <%= experience.skill.name %>
      </li>
    <% end %>
  </ul>

 <label class="control-label-static">Section Preferences</label>
  <ul class="list-group">
    <% @user.section_preferences.each do |section_preference| %>
      <li class="list-group-item">
        <span class="label label-primary"><%= section_preference.value %></span>
        <span class="label label-warning"><%= section_preference.section.term %></span>

        <%= section_preference.section.course.label %>
        (<%= section_preference.section.cc_instructor_tag %>)
      </li>
    <% end %>
  </ul>
<% end %>

<% if @user.is_instructor %>
 <label class="control-label-static">Student Preferences</label>
  <ul class="list-group">
    <% @user.student_preferences.each do |student_preference| %>
        <% unless !student_preference.student %>

      <li class="list-group-item">
        <h5 class="list-group-item-heading"><%= student_preference.student.full_name %>
        - <%= student_preference.section.course.label %></h5>
        <p class="list-group-item-text">
          <span class="label label-primary"><%= student_preference.value %></span>
          <span class="label label-danger"><%= student_preference.student.is_wait_list ? "Wait-List" :""  %></span>
          <span class="label label-warning"><%= student_preference.section.term %></span>

        </p>
      </li>
          <% end %>

    <% end %>
  </ul>

 <label class="control-label-static">Sections</label>
  <ul class="list-group">
    <% @user.sections.where(show: true).each do |section| %>
      <div class="list-group-item">
        <h5 class="list-group-item-heading"><%= section.course.name %></h5>
        <p class="list-group-item-text">
        <span class="label label-primary"><%= section.merge_label %></span>
        <span class="label label-warning"><%= section.term %></span>
        <span class="label label-primary"><%= section.location %></span>
        <span class="label label-success"><%= "#{section.current_enrollment} / #{section.max_enrollment} students" %></span>
        </p>
      </div>
    <% end %>
  </ul>
<% end %>
 </div>

app/views/administrator/users/index.html.erb
<%= link_to "&larr; Back to Settings".html_safe, administrator_settings_path %>

<h2>Users</h2>
<% unless (params[:status] == "all") %>

		<%unless(params[:status] == "Instructor") %>
    	<%= link_to "New " + params[:status] , new_administrator_user_path(:status => params[:status] ), class: "btn btn-success"  %>
	   <%end%>
	   
	    <% unless (params[:status] == "Administrator") %>
	 
	 <%if (params[:status] == "Student") %>
	    	<%= link_to "Import " + params[:status] , new_administrator_user_import_path(:status => params[:status] ), class: "btn btn-success"  %>
	  <%end%>
	    	<div class = "pull-right">
	 	    <%= link_to "Delete All " + params[:status] + "s" , destroyAll_administrator_users_path( :status => params[:status]), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-danger " %>
	   	 	<%= link_to "Ignore All " + params[:status] + "s" , reset_administrator_users_path( :status => params[:status]), method: :put, data: {confirm: "Are you sure?"}, class: "btn btn-warning" %>
	   	 	</div>
	   	 	

	     <% end %>
    <% end %>
<br>
<br>


<% @i = 0 %>

<table class="table">
  <thead>
    <th></th>
    <th> ID </th>
    <th>First Name</th>
    <th>Last Name</th>
    <th>Email</th>
    <th>Role</th>
    <% if params[:status] == "Student" %>
    <th>FTE</th>
    <th>Major</th>
    <th>Wait-list</th>
    <th>Is_Admin</th>


  <%end%>

<% if params[:status] == "all" %>
    <th>Is_Administrator</th>
    <th>Considered</th>

<% end%>
    <th></th>

  </thead>

  <tbody>
    <%= render @users %>
  </tbody>
</table>

app/views/administrator/users/new.html.erb
<%= link_to "&larr; Back to Users".html_safe, administrator_users_path(:status => params[:status] ) %>

<h1>New User</h1>

<%= render 'form' %>

app/views/administrator/users/show.html.erb
<%= link_to "&larr; Back to Users".html_safe, administrator_users_path(:status => params[:status] ) %>
<br><br>
<div class="row">
  <div class="form-group">
   <div class="col-sm-2">
      <label class="control-label-static">First Name</label>
    </div>
    <div class="col-sm-10">
      <p class="form-control-static"><%= @user.first_name %></p>
    </div>
  </div>
  
  <div class="form-group">
   <div class="col-sm-2">
      <label class="control-label-static">Last Name</label>
    </div>
    <div class="col-sm-10">
      <p class="form-control-static"><%= @user.last_name %></p>
    </div>
  </div>
  
  
    <div class="form-group">
   <div class="col-sm-2">
      <label class="control-label-static">Email</label>
    </div>
    <div class="col-sm-10">
      <p class="form-control-static"><%= @user.emails %></p>
    </div>
  </div>
  
     <div class="form-group">
   <div class="col-sm-2">
      <label class="control-label-static">Role</label>
    </div>
    <div class="col-sm-10">
      <p class="form-control-static"><%= @user.role %></p>
    </div>
  </div>


 <div class="form-group">
   <div class="col-sm-2">
      <label class="control-label-static">FTE</label>
    </div>
    <div class="col-sm-10">
      <p class="form-control-static"><%= @user.fte %></p>
    </div>
  </div>
  
     <div class="form-group">
   <div class="col-sm-2">
      <label class="control-label-static">Is in wait-list</label>
    </div>
    <div class="col-sm-10">
      <p class="form-control-static"><%= @user.is_wait_list ? "Yes" : "No" %></p>
      <br>
    </div>
  </div>
 


<% if @user.is_student %>
 
<label class="control-label-static">Experience</label>
  <ul class="list-group">
    <% @user.experiences.each do |experience| %>
      <li class="list-group-item">
        <span class="label label-primary"><%= experience.value %></span>
        <%= experience.skill.name %>
      </li>
    <% end %>
  </ul>

 <label class="control-label-static">Section Preferences</label>
  <ul class="list-group">
    <% @user.section_preferences.each do |section_preference| %>
      <li class="list-group-item">
        <span class="label label-primary"><%= section_preference.value %></span>
        <%= section_preference.section.course.label %>
        (<%= section_preference.section.cc_instructor_tag %>)
      </li>
    <% end %>
  </ul>
<% end %>

<% if @user.is_instructor %>
 <label class="control-label-static">Student Preferences</label>
  <ul class="list-group">
    <% @user.student_preferences.each do |student_preference| %>
    <% unless !student_preference.student %>

      <li class="list-group-item">
        <h5 class="list-group-item-heading"><%= student_preference.student.full_name %>
        - <%= student_preference.section.course.label %></h5>
        <p class="list-group-item-text">
          <span class="label label-primary"><%= student_preference.value %></span>
          <span class="label label-danger"><%= student_preference.student.is_wait_list ? "Wait-List" :""  %></span>

        </p>
      </li>
          <% end %>

    <% end %>
  </ul>

 <label class="control-label-static">Sections</label>
  <ul class="list-group">
    <% @user.sections.each do |section| %>
      <div class="list-group-item">
        <h5 class="list-group-item-heading"><%= section.course.name %></h5>
        <p class="list-group-item-text">
        <span class="label label-warning"><%= section.term %></span>
        <span class="label label-primary"><%= section.location %></span>
        <span class="label label-success"><%= "#{section.current_enrollment} / #{section.max_enrollment} students" %></span>
        </p>
      </div>
    <% end %>
  </ul>
<% end %>

<%= link_to 'Edit', edit_administrator_user_path(@user, :status => params[:status]), class: "btn btn-default" %>