config/routes.rb
Rails.application.routes.draw do

  get 'help/index'

  namespace :administrator do
  get 'sections/_section'
  end

  namespace :administrator do
  get 'sections/index'
  end

  namespace :administrator do
  get 'sections/show'
  end

  namespace :administrator do
  get 'students/index'
  end

  namespace :administrator do
  get 'students/_student'
  end

  namespace :administrator do
  get 'students/show'
  end

  namespace :administrator do
  get 'students/edit'
  end
  
  namespace :administrator do
  get 'admin_section_preferences/_admin_section_preferences'
  end

  namespace :administrator do
  get 'admin_section_preferences/index'
  end

  namespace :administrator do
  get 'admin_section_preferences/show'
  end

  get 'white_courses/index'

  get 'courses/Sync'

  get 'courses/index'

  root 'pages#index'

  devise_for :users, :controllers => {
    :omniauth_callbacks => "users/omniauth_callbacks"
  }

  resources :skills
  
  resources :student do 
  	
  	  # Students
  	resources :section_preferences do 
    	collection do
    		post :collect_pref
    		
    	end
    end
  resources :experiences do
    	collection do
    		post :collect_experiences
    	end
    end
  	
  	
  end



  # Instructors
  resources :sections do
  	post :comment
    resources :student_preferences do 
    	collection do
    		
    		post :collect_pref
    		
    	end
    end
    
    resources :requirements do
    	collection do
    		post :collect_requirements
    	end
    end
  end

  namespace :administrator do

    resources :departments
    resources :section_imports
    resources :white_courses do 
    	collection do
	    	post :update_term
	    	put :ignoreSelectedCourses
	    	put :backSelectedCourses
	        post :cross
	        post :config_constants
	        get :cross_listed
    	end
    
    delete :deleteCross
    	
   end
    
    resources :courses do
    	collection do
    		delete :deleteAllSections
	    	get :editAll
	    	get :deleteSections
	    	post :create
	    	delete :deleteSelectedSections
	    	get :adjustSections
	    	put :adjustSelectedSections 
	    	post :updateSectionsInfo
	    	post :do_update_Sections
    	end
    end
    resources :sections
    resources :email do
      collection do
        post  :sendmail
        end
      end
    resources :keep_users do 
    	collection do
   			 post :addUsers
  		end
    end
    resources :users do
    	collection do
    		delete :destroyAll
    		put :reset
  		end
  	
  	
  		put :wait_list
  		put :off_wait_list
  		put :un_consider

     end
    
    resources :assignments do
    	get :no_stat_edit

      #collection do
        get :send_assignments_CS
        get :send_assignments_non_CS
      #end
    end

    resources :user_imports
    
    get 'settings' => 'settings#index'
    post 'settings/current_term' => 'settings#set_current_term'
    post 'settings/synchronizeGTA' => 'settings#synchronizeGTA'
   	post 'settings/synchronizeIns' => 'settings#synchronizeIns'
    post 'settings/synchronize' => 'settings#synchronize'
    get 'settings/section_preferences_cs' => 'settings#section_preferences_cs'
    get 'settings/section_preferences_ece' => 'settings#section_preferences_ece'
    get 'settings/student_preferences' => 'settings#student_preferences'
    get 'settings/sections' => 'settings#sections'
    get 'settings/gta_template' => 'user_imports#gta_template'
    get 'settings/instructor_template' => 'user_imports#instructor_template'
    get 'settings/sections_template' => 'courses#sections_template'


  end
 
   match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]
end

app/models/experience.rb
class Experience < ActiveRecord::Base
  enum value: {
    :"Qualified"          => 2,
    :"Slightly qualified" => 1,
    :"Unqualified"        => 0,
  }

  validates_uniqueness_of :student_id, scope: [:skill_id]

  validates_presence_of :student_id
  validates_presence_of :skill_id
  validates_presence_of :value

  belongs_to :skill
  belongs_to :student, class_name: "User"
end

app/controllers/experiences_controller.rb
class ExperiencesController < ApplicationController
  before_action :set_experience, only: [:show, :destroy]
  before_filter :set_skills
   before_action :set_student

  def new
    @experience = @student.experiences
  end

 def collect_experiences
 	
 	if params["skill_value"] == nil
 			 #render "new"
 			   redirect_to new_student_experience_path(@student), alert: 'No Experiences added.'

		else
      		redirect_to student_path(@student), notice: 'Experience was successfully created.'
		
 		 @skills.each do |skill|
 			val = params["skill_value"]["#{skill.id}"]		
	   		unless val == nil
	   			
	   			@exp =  @student.experiences.where(skill_id: skill.id , student_id: @student.id).take
	   			
	   			if @exp  == nil
	   				
	   				@student.experiences.create({skill_id: skill.id, value: val })
	   				
	   			else
	   				
	   				@exp.update_attributes({value: val})
	   				
	   			end
	   			
	   		end
		 end
 	
 		end

	
 end

  def create
    @experience = @user.experiences.new(experience_params)

    if @experience.save
      redirect_to student_path(@student), notice: 'Experience was successfully created.'
    else
      render :new
    end
  end

  def destroy
    @experience.delete
    redirect_to student_path(@student), notice: 'Experience was successfully destroyed.'
  end

  private

  def set_experience
    @experience = Experience.find(params[:id])
  end

 def set_skills
 	    @skills = Skill.all
 end

  def experience_params
    params[:experience].permit(:skill_id, :value)
  end
 
 
 def set_student
 	@student = User.find(params[:student_id])
 	end
end

app/views/experiences/_experience.html.erb
<div class="list-group-item">
  <span class="label label-primary" skill=<%= experience.skill.name %>><%= experience.value %></span>
  <%= experience.skill.name %>
 

  <% unless params[:action] == "new" %>
  <div class="pull-right">
    <%= button_to "Remove", student_experience_path( @student, experience), method: :delete,
      class: "btn btn-danger btn-xs",
      data: { confirm: "Are you sure?" } %>
  </div>
  <%end%>
  
  
</div>

app/views/experiences/_form.html.erb
  <style>
  .radio-inline {
    vertical-align: center;
  }
  </style>
  
   <%= form_tag(collect_experiences_student_experiences_path , method: "post") do %>

    <% unless @skills.empty? %>
    <div class="list-group">

     <table class="table" style="width: 80%;">

      <tr>
        <th style="text-align:"></th>
        <th class="select_pref"><h10> 2 =  "Qualified"  <br> 1 = "Slightly Qualified" <br> 0 = "Unqualified" </h10> </th>
      </tr>
      
       <% @skills.each do |skill| %>
       <tr>
 		<td>
 	 		<%= skill.name %>
		</td>
		
		<td>
		<div  class="checkboxgroup" >
		
		       <% Experience.values.each do |option| %>

			 <label class="radio-inline">
				<% @exp =  @student.experiences.where(skill_id: skill.id , student_id: @student.id, value: option[1]).take %>
		   		<% checked = @exp ? "checked=checked" : "" %>
         		 <input style="vertical-align: middle" type="radio" name=<%="skill_value[#{skill.id}]" %> value= "<%= option[0] %>" <%= checked %>> <%= option[1] %>
       		 </label>
        <%end%>
        </div>
		</td>
      </tr>

        <% end %>
        
	<% end %>

	</table>
	
	<%= submit_tag "Submit", class: "btn btn-success", data: {confirm: "Are you sure?"}  %>
	 <%= link_to 'Back', student_path(@student), class: "btn btn-default" %>
	<br>

	<% end %>


  </div>
  

  

app/views/experiences/new.html.erb
<h2>New experience</h2>

<%= render 'form' %>